### ISSUE TITLE
LocalGov Alert Banner: specification for targetted alerts

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#120]
This issue is to help prepare and approve the specification for changes to the alert banner to support greater control over where alert banners are displayed on a site. 

## User story (example)

**As a** content designer

**I want to** publish an alert banner that only displays on /events section of the site

**So that** I can add a warning about COVID-19 safety at co-located events. 

## User story (example)

**As a** content designer

**I want to** publish an alert banner that only displays on news items

**So that** I can add a notice about our communications department.

**Comment by finnlewis** [comment]
@andybroomfield @willguv 

Do we already have any defined specification than that on https://trello.com/c/ML8TaTYD/288-targeting-alerts-to-a-specific-page ?

Should we arrange a call to confirm where the main drivers for this are coming from?

**Comment by willguv** [comment]
@finnlewis are we using the first regular story refinement session for this? Monday pm fortnightly? I think you were going to invite people. I can if not

**Comment by andybroomfield** [comment]
> ## User story (example)
> **As a** content designer
> 
> **I want to** publish an alert banner that only displays on /events section of the site
> 
> **So that** I can add a warning about COVID-19 safety at co-located events.
> 

That can be achieved with existing functionlity.

1. Create a new alert banner type for event banners
2. Create a new alert banner block and select only display banners of type event, and remove event banners from the main block.
3. Set the conditions on the newly created events block to only display on the /events* path


> ## User story (example)
> **As a** content designer
> 
> **I want to** publish an alert banner that only displays on news items
> 
> **So that** I can add a notice about our communications department.

Same as above.

I think where it gets more complicated is if you have more complex conditions and don't want to have to manage new alert banner types and blocks for every scenario. I've been exploring using [condition field](https://www.drupal.org/project/condition_field) on the banner entity and had good results, although it did require adding a custom hook.

It does raise the question of how much functionality we want to actully support within the modules, and how much we would expect a council / orgnaisation to be able to build themselves. The reason we made this change to making alert banner an entity in its own right instead of just a text box was so that it can be leveraged with all of Drupals functionality. 
This doens't mean not to include it, just to raise it as something we genuinly expect the module to provide and to make sure we don't end up trying to build things that cover every use case.

**Comment by finnlewis** [comment]
Just to note, update on the Trello card:  

> Ben Hills-Jones 31 minutes ago
> @willcallaghan So the types of content is the examples I gave earlier. Temporary alert style information telling users that something is changing, or happening, but is more specific that an entire section like all of streets and transport. The length I think would be pretty short. For example this was what was added about changes to emission based parking New emission based pay & display charges will commence from Monday 15 March 2021 across the borough. For the emission based discount you must use our mobile pay facility at the time of parking
> 
> I am very unfamiliar with service status and how that would display on a page but I think in principle yes that sounds like it might suffice IF you can target where it is displayed.
> 
> I think any type of content might need this message displayed on it, not just service pages.
> 
> Expiry dates where it would auto publish would be fantastic.

**Comment by andybroomfield** [comment]
User story on the Trello card
> "As a content designer, I need to be able to add and display a temporary message on any page on the website, or a collection of pages, so i can inform users of a change to a service"

**Comment by finnlewis** [comment]
I think we can call this done, with enough spec on the Miro board: https://miro.com/app/board/o9J_lHm9M2s=/
