### ISSUE TITLE
Is it nessecary to clear the cache when publishing a banner? (Improve cache tags / contexts)

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_alert_banner#126]
There is quite a performance slump when publishing a new alert banner, as the cache needs to be cleared.
Lets improve the cache tags / contexts as we should be able to rely on those for banner publication.

**Comment by stephen-cox** [comment]
I suspect this is due to no cache contexts and tags being added to the [AlertBannerBlock](https://github.com/localgovdrupal/localgov_alert_banner/blob/1.x/src/Plugin/Block/AlertBannerBlock.php) class.

My suggestion is to set the cache contexts and tags in the `AlertBannerEntity` class in `getCacheContext` and `getCacheTag` methods, rather than the [hook_entity_build_defaults_alter](https://github.com/localgovdrupal/localgov_alert_banner/blob/ee7fafe8c896ba2af7524193163653dd7522177f/localgov_alert_banner.module#L30) function and then have the blocks `getCacheContext` and `getCacheTag` methods set these from the entity class.

If that doesn't work it should be possible to have the entity class explicitly invalidate tags used by the block in the `preSave` method.

**Comment by Adnan-cds** [comment]
Ah Andy, Steve,
This has bitten me again :(  I should have [spotted this](https://github.com/localgovdrupal/localgov_alert_banner/blob/3e40ca834d416023d40ed178ef5054cc031119f8/src/Entity/AlertBannerEntity.php#L166) while reviewing the [other cache tag related PR](https://github.com/localgovdrupal/localgov_alert_banner/pull/155/files).  Perhaps we should get rid of the call to ```drupal_flush_all_caches();``` now.
