### ISSUE TITLE
Full page alert banner

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_alert_banner#134]
*Copy-pasting from the related Croydon ticket:*
> When a notable person dies, there is a strict protocol for the council to follow to publicise information about the death.

> A full-page takeover is the recommended response for all users when they visit the site, with a consistent site wide alert present as the user navigates the site.

Pull request: #133

**Comment by andybroomfield** [comment]
Thanks for the work @Adnan-cds.
I'm not so sure it should be directly integrated with the alert banner module, which is targeted for content designers to easily add a banner at the top of the page, following the [Gov.uk emergency banner pattern](https://docs.publishing.service.gov.uk/manual/emergency-publishing.html#death-of-a-notable-person). 
The full page alert feature originated as a requirment from Lambeth, and later Croydon.
BHCC implements the Gov.uk pattern only.
I'd like to take this back to the product group (@willguv) to check first if this is a feature that many councils are looking to adopt.
I also have accessibliy and usability concerns about a full screen takeover and would like to get some more details on the impact of this (@danchamp) and any supporting user research.

In terms of ways forward, I see three options.
- Add this to the module, but have it as a submodule so its there as an option.
- Croydon release it as an independent module, which uses localgov_alert_banner as a dependency.  
- We use this code in a [localgov_examples module](https://github.com/localgovdrupal/localgov/issues/159) to demonstrate how councils can extend the alert banner to thier specific needs.

The Alert banners, and all code we produce is by design extendable by any council / organisation picking up the modules. So it may not be necessary to include every development and feature request into the modules, though we should find other ways to share development.

**Comment by willguv** [comment]
Hi @andybroomfield @Adnan-cds, this came up in a conversation a while ago. While PMs didn't decide formally whether to include it, there did seem to be a lot of interest. It feels like we should add it as an option to be used or not. I'm keen to hear from content designers (we need a few more in the group) whether they would use it.

Before we do that though, can you share your accessibility and usability concerns please? @andybroomfield and @danchamp (and anyone who's interested)

**Comment by danchamp** [comment]
There are some accessibility issues, I'll review as soon as I can.

**Comment by andybroomfield** [comment]
@willguv Full screen takeovers when a user is trying to get something done are considered bad. Especially if they block a user from getting something done, and as seen from some deploys, causes unexpected issues with disabling page scroll making dismissing it hard.
I'd like to see the user research / accesibitly studies on them. I'm interested to know why gov.uk goes for the banner approach instead of the takeover. 
I know there are differences in authority approaches, my query here is to ask if partner councils expected to see included (go with the sub module approach), or if its something that would fit into a larger localgov_drupal ecosystem (the independant module / localgov_examples approach).
Do we have a process for how new features are proposed / accepted?
