### ISSUE TITLE
Should we remove role="alert" from alert banners

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_alert_banner#146]
When testing a page in AXE, I am told that `role="alert"` is not valid on the article element.

Two things we can do:
1. Remove the `article` element and place a `div` there instead, or
2. remove the `role="alert"` attribute.

I'm open to debate on this one, but I _think_ role="alert" may not be correct here. I think that type alert is for dynamic content, such as form validation if someone hasn't filled out a form properly for example. 

Here's the MDN notes on it:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

and some notes on live regions
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

**Comment by andybroomfield** [comment]
Is there an alternative role that should be used?
It is important that the alerts have a sense of gravitas, as they are used for emergencies.
I'm still confused why an alert is an article TBH... 

Do we know what other sites do. I was checking gov.uk and national rail, but there COVID banners just use plain div with no role.

**Comment by markconroy** [comment]
I think the reason role="alert" might not be needed is because it is not for info that is updating on the site as you are looking at it - such as via a ajax call. It's not something like a form being filled out, but a field was missed, or ordering something in a shop, but the website realises the item is now out of stock.

We can remove the `article` if you wish. Might be best to follow the pattern govuk is using, and leave in role="article".

**Comment by andybroomfield** [comment]
@markconroy I found the markup they use
https://github.com/alphagov/govuk-emergency-banners/blob/master/app/views/_emergency_banner.html
They use role="banner"

**Comment by danchamp** [comment]
Using `role="alert"` is borderline acceptable - it's for important information the user needs to consume, which isn't restricted to errors, but is really designed for dynamically generated content.

Browsers will announce the alert to screen readers but not move the focus to it, which makes it trickier for users to dismiss it than if it had focus. If they don't dismiss it, it will be back again on every page. That said we do make it easy to hide.

Some user testing on this would be ideal.

There should only be one `role="banner"` on a page, and we're already using it for the header (which is a good use for it), so that would also need to change if it was to be used for alert banners, then there's an issue if there's more than one active banner.

**Comment by markconroy** [comment]
We don't have `role="banner"` on the header of the new theme. I can add it in, but it didn't seem necessary.

**Comment by danchamp** [comment]
> We don't have `role="banner"` on the header of the new theme. I can add it in, but it didn't seem necessary.

Definitely not necessary with the `<header>` container being used which has an implicit role of banner. It's used in localgov_theme for IE11 compatability.

**Comment by danchamp** [comment]
Some more evidence that `role="alert"` is not appropriate for alert banners. From [WAI-ARIA](https://www.w3.org/TR/wai-aria-1.1/#alert):

> Alerts are assertive live regions and will be processed as such by assistive technologies. Neither authors nor user agents are required to set or manage focus to them in order for them to be processed. Since alerts are not required to receive focus, content authors **SHOULD NOT** require users to close an alert.

> If an alert requires focus to close the alert, then content authors **SHOULD** use alertdialog instead.

If we really want the alert to be announced to the user, alertdialog looks like the best option. Otherwise we copy govuk and use a div with `role="banner"`, and possibly wrap multiple alerts in a single div?

**Comment by andybroomfield** [comment]
Did this discussion get resolved? Should we now go ahead and remove this?
