### ISSUE TITLE
LocalGov Scarfolk sub-theme - support optional block placement 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_alert_banner#175]
See https://github.com/localgovdrupal/localgov/issues/379

**Comment by andybroomfield** [comment]
Shouldn't Localgov_scarfolk be providing responsibility for these blocks and not the modules?
I assume scaffold is the equivalent of Umami, but it not intended as what councils build with.
So I'm not sure it makes sense to change the blocks here to use Scarfolk.
Also not all tests use scarfolk, but many use localgov_base to get the blocks installed.
If the PR is enacted, I assume those sites using [config_distro](https://www.drupal.org/project/config_distro) / config_syncronizer are going to have to ignore this config change otherwise our site blocks may get deleted (something that has to be checked).
So for those reasons, I recommend the blocks are left as is in the module and scarfolk provides its own block configuration.

(Commenting here as I don't see a base issue for changing the block configuration).
