### ISSUE TITLE
Fix code depreactions for phpstan 1.x (required for PHP 8.1)

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_alert_banner#198]
We need to upgrade phpstan to 1.x for PHP 8.1. This highlights the following issues:

```
 ------ ----------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_alert_banner/src/Form/AlertBannerEntityDeleteForm.php                                                           
 ------ ----------------------------------------------------------------------------------------------------------------------------------------- 
  12     Class Drupal\localgov_alert_banner\Form\AlertBannerEntityDeleteForm extends @internal class Drupal\Core\Entity\ContentEntityDeleteForm.  
         💡 Extend \Drupal\Core\Entity\ContentEntityConfirmFormBase. See https://www.drupal.org/node/2491057                                      
 ------ -----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by andybroomfield** [comment]
Discussion on https://www.drupal.org/node/2491057 is unclear whether we should proceed, however I've opened up a new PR in an attempt to address this since the core class does exist.

**Comment by andybroomfield** [comment]
Trying to understand the issue, is it that we should remove and just use the generic ContentEntityDeleteForm instead of extending it? As we don't override anything.
Looking at localgov_geo for how it handles entity deletion, [it does not include its own entity delete form](https://github.com/localgovdrupal/localgov_geo/blob/bf12233a55c2a41162965ddedfb180880e1b895f/src/Entity/LocalgovGeo.php#L30).
I think that is the better method to use.
