### ISSUE TITLE
Banner create and set live flow

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_alert_banner#70]
> And a new issue for the modal / if we should remove publish from the form (I'd prefer to keep it there as emergency publishers may be needing to write these banners in an emergency, but can be discussed the best implementation).

The flow for creation of banners would become.

Go direct to the create form. 
Submit. 
Get redirected to {banner-path}/status where you get a preview and asked if you want to 'set this live?'

Otherwise you are on the list of banners. Where there are the 'set this live' 'remove this' links on existing banners, if the form is displayed in a modal or a link as now is an enhancement. And there is the link to create new, flow above.

_Originally posted by @ekes in https://github.com/localgovdrupal/localgov_alert_banner/pull/68#issuecomment-656637742_

**Comment by andybroomfield** [comment]
I will check this with BHCC comms team to see if it works ok for them.
At present in BHCC, the put live uses the checkbox on the banner itself (although we also shortcut the admin screens to only ever editing a single banner).
The main concern is to avoid user confusion when a banner needs to be put live quickly, whilst still having some confirmation to prevent a banner going live if its just being drafted for future use.
Also would the extra step apply even if a user was not intending to put the banner live, but just writing one for future use? My current thoughts are that I think it should only trigger the confirmation step when there is explicit user confimration that they wish to put the banner live, otherwise it should go back to the list of alert banners.

**Comment by ekes** [comment]
> Also would the extra step apply even if a user was not intending to put the banner live, but just writing one for future use? My current thoughts are that I think it should only trigger the confirmation step when there is explicit user confimration that they wish to put the banner live, otherwise it should go back to the list of alert banners.

Actually that would be simple enough:-

Remove the published checkbox from the form.
Place a non-field checkbox on the form that says 'I want to set this live directly'.
On submission of the entity form if set the destination based on the value of that checkbox.

**Comment by ekes** [comment]
So I wasn't intending on doing this directly, but before I closed the files quickly: https://github.com/localgovdrupal/localgov_alert_banner/commit/daaca478d246c262c439218e0d58b44664e72abb

No tests. So if someone wants to write them that would be great.
Also it redirects to the .collection list which is currently the coded generated one for the bundle. That would be updated and made nicer by getting rid of the individual per-bundle ones, and overriding the entity one, which is the paths #65 issue.

**Comment by andybroomfield** [comment]
Discovered this doesn't override the destination parementer so I will add fix for that.

**Comment by andybroomfield** [comment]
Initial work in #71 if you want to do an inital review @ekes
